/* tslint:disable */
/* eslint-disable */
/**
 * Chattly Service
 * This service provides endpoints for all `chattly` related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';
/**
 * Response object for chat-connection created
 * @export
 * @interface CreateSingleChatConnectionResponse
 */
export interface CreateSingleChatConnectionResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateSingleChatConnectionResponse
     */
    chatMessage: string;
    /**
     * 
     * @type {User}
     * @memberof CreateSingleChatConnectionResponse
     */
    newConnectUser: User;
}
