/* tslint:disable */
/* eslint-disable */
/**
 * Chattly Service
 * This service provides endpoints for all `chattly` related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Group chat object
 * @export
 * @interface GroupChat
 */
export interface GroupChat {
    /**
     * 
     * @type {string}
     * @memberof GroupChat
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GroupChat
     */
    description?: string;
    /**
     * Image url for group-chat
     * @type {string}
     * @memberof GroupChat
     */
    image?: string;
}
