/* tslint:disable */
/* eslint-disable */
/**
 * Chattly Service
 * This service provides endpoints for all `chattly` related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Create group-char request data
 * @export
 * @interface CreateGroupChatDto
 */
export interface CreateGroupChatDto {
    /**
     * 
     * @type {string}
     * @memberof CreateGroupChatDto
     */
    name: string;
    /**
     * List of usernames or members for group chat
     * @type {Array<string>}
     * @memberof CreateGroupChatDto
     */
    members: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateGroupChatDto
     */
    description?: string;
    /**
     * Group chat display image
     * @type {Blob}
     * @memberof CreateGroupChatDto
     */
    image?: Blob;
    /**
     * Optional chat message. A default `greeting` message will be sent if not provided
     * @type {string}
     * @memberof CreateGroupChatDto
     */
    initialChatMessage?: string;
}
