/* tslint:disable */
/* eslint-disable */
/**
 * Chattly Service
 * This service provides endpoints for all `chattly` related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LoginDto
 */
export interface LoginDto {
    /**
     * User's username in platform
     * @type {string}
     * @memberof LoginDto
     */
    username?: string;
    /**
     * User's email
     * @type {string}
     * @memberof LoginDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginDto
     */
    password: string;
}
