/* tslint:disable */
/* eslint-disable */
/**
 * Chattly Service
 * This service provides endpoints for all `chattly` related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChatType } from './chat-type';
/**
 * Send chat-message request data
 * @export
 * @interface SendChatMessageDto
 */
export interface SendChatMessageDto {
    /**
     * 
     * @type {string}
     * @memberof SendChatMessageDto
     */
    content: string;
    /**
     * ID of the receiver, which can be for either SINGLE-CHAT or GROUP-CHAT
     * @type {string}
     * @memberof SendChatMessageDto
     */
    recipientID: string;
    /**
     * 
     * @type {ChatType}
     * @memberof SendChatMessageDto
     */
    recipientType?: ChatType;
}
