/* tslint:disable */
/* eslint-disable */
/**
 * Chattly Service
 * This service provides endpoints for all `chattly` related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Update group-chat request data
 * @export
 * @interface UpdateGroupChatDto
 */
export interface UpdateGroupChatDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateGroupChatDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateGroupChatDto
     */
    description?: string;
    /**
     * Group chat display image
     * @type {Blob}
     * @memberof UpdateGroupChatDto
     */
    image?: Blob;
}
