/* tslint:disable */
/* eslint-disable */
/**
 * Chattly Service
 * This service provides endpoints for all `chattly` related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Role } from './role';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * User unique identifier
     * @type {string}
     * @memberof User
     */
    id: string;
    /**
     * User's username in platform
     * @type {string}
     * @memberof User
     */
    username: string;
    /**
     * User's email
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * 
     * @type {Role}
     * @memberof User
     */
    role: Role;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    chatDisplayName: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    active: boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    imageURL?: string;
    /**
     * User biography (information about user)
     * @type {string}
     * @memberof User
     */
    bio?: string;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    lastLoginAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    updatedAt: Date;
}
